insert into ytp.tipo_usuario(tipo) values('administrador');
insert into ytp.tipo_usuario(tipo) values('usuario');
insert into ytp.tipo_usuario(tipo) values('empresa');
insert into ytp.tipo_usuario(tipo) values('particular');

insert into ytp.categoria(nombre) values('retail');
insert into ytp.categoria(nombre) values('otros');

insert into ytp.pais(nombre) values('Chile');

insert into ytp.ciudad(nombre,idPais) values('Arica',1);
insert into ytp.ciudad(nombre,idPais) values('Putre',1);
insert into ytp.ciudad(nombre,idPais) values('Iquique',1);
insert into ytp.ciudad(nombre,idPais) values('Pozo Almonte',1);
insert into ytp.ciudad(nombre,idPais) values('Antofagasta',1);
insert into ytp.ciudad(nombre,idPais) values('Calama',1);
insert into ytp.ciudad(nombre,idPais) values('Tocopilla',1);
insert into ytp.ciudad(nombre,idPais) values('Cha�aral',1);
insert into ytp.ciudad(nombre,idPais) values('Copiap�',1);
insert into ytp.ciudad(nombre,idPais) values('Vallenar',1);
insert into ytp.ciudad(nombre,idPais) values('Illapel',1);
insert into ytp.ciudad(nombre,idPais) values('Coquimbo',1);
insert into ytp.ciudad(nombre,idPais) values('Ovalle',1);
insert into ytp.ciudad(nombre,idPais) values('Hanga Roa',1);
insert into ytp.ciudad(nombre,idPais) values('Los Andes',1);
insert into ytp.ciudad(nombre,idPais) values('Quilpu�',1);
insert into ytp.ciudad(nombre,idPais) values('La Ligua',1);
insert into ytp.ciudad(nombre,idPais) values('Quillota',1);
insert into ytp.ciudad(nombre,idPais) values('San Antonio',1);
insert into ytp.ciudad(nombre,idPais) values('San Felipe',1);
insert into ytp.ciudad(nombre,idPais) values('Valpara�so',1);
insert into ytp.ciudad(nombre,idPais) values('Rancagua',1);
insert into ytp.ciudad(nombre,idPais) values('Pichilemu',1);
insert into ytp.ciudad(nombre,idPais) values('San Fernando',1);
insert into ytp.ciudad(nombre,idPais) values('Cauquenes',1);
insert into ytp.ciudad(nombre,idPais) values('Curic�',1);
insert into ytp.ciudad(nombre,idPais) values('Linares',1);
insert into ytp.ciudad(nombre,idPais) values('Talca',1);
insert into ytp.ciudad(nombre,idPais) values('Lebu',1);
insert into ytp.ciudad(nombre,idPais) values('Los �ngeles',1);
insert into ytp.ciudad(nombre,idPais) values('Concepci�n',1);
insert into ytp.ciudad(nombre,idPais) values('Chill�n',1);
insert into ytp.ciudad(nombre,idPais) values('Temuco',1);
insert into ytp.ciudad(nombre,idPais) values('Angol',1);
insert into ytp.ciudad(nombre,idPais) values('La Uni�n',1);
insert into ytp.ciudad(nombre,idPais) values('Valdivia',1);
insert into ytp.ciudad(nombre,idPais) values('Castro',1);
insert into ytp.ciudad(nombre,idPais) values('Puerto Montt',1);
insert into ytp.ciudad(nombre,idPais) values('Osorno',1);
insert into ytp.ciudad(nombre,idPais) values('Chait�n',1);
insert into ytp.ciudad(nombre,idPais) values('Puerto Ays�n',1);
insert into ytp.ciudad(nombre,idPais) values('Cochrane',1);
insert into ytp.ciudad(nombre,idPais) values('Coyhaique',1);
insert into ytp.ciudad(nombre,idPais) values('Chile Chico',1);
insert into ytp.ciudad(nombre,idPais) values('Puerto Williams',1);
insert into ytp.ciudad(nombre,idPais) values('Punta Arenas',1);
insert into ytp.ciudad(nombre,idPais) values('Porvenir',1);
insert into ytp.ciudad(nombre,idPais) values('Puerto Natales',1);
insert into ytp.ciudad(nombre,idPais) values('Colina',1);
insert into ytp.ciudad(nombre,idPais) values('Puente Alto',1);
insert into ytp.ciudad(nombre,idPais) values('San Bernardo',1);
insert into ytp.ciudad(nombre,idPais) values('Melipilla',1);
insert into ytp.ciudad(nombre,idPais) values('Santiago',1);
insert into ytp.ciudad(nombre,idPais) values('Talagante',1);

insert into ytp.comuna(nombre,idCiudad) values('Arica',1);
insert into ytp.comuna(nombre,idCiudad) values('Camarones',1);
insert into ytp.comuna(nombre,idCiudad) values('General Lagos',2);
insert into ytp.comuna(nombre,idCiudad) values('Putre',2);
insert into ytp.comuna(nombre,idCiudad) values('Alto Hospicio',3);
insert into ytp.comuna(nombre,idCiudad) values('Iquique',3);
insert into ytp.comuna(nombre,idCiudad) values('Cami�a',4);
insert into ytp.comuna(nombre,idCiudad) values('Colchane',4);
insert into ytp.comuna(nombre,idCiudad) values('Huara',4);
insert into ytp.comuna(nombre,idCiudad) values('Pica',4);
insert into ytp.comuna(nombre,idCiudad) values('Pozo Almonte',4);
insert into ytp.comuna(nombre,idCiudad) values('Antofagasta',5);
insert into ytp.comuna(nombre,idCiudad) values('Mejillones',5);
insert into ytp.comuna(nombre,idCiudad) values('Sierra Gorda',5);
insert into ytp.comuna(nombre,idCiudad) values('Taltal',5);
insert into ytp.comuna(nombre,idCiudad) values('Calama',6);
insert into ytp.comuna(nombre,idCiudad) values('Ollag�e',6);
insert into ytp.comuna(nombre,idCiudad) values('San Pedro de Atacama',6);
insert into ytp.comuna(nombre,idCiudad) values('Mar�a Elena',7);
insert into ytp.comuna(nombre,idCiudad) values('Tocopilla',7);
insert into ytp.comuna(nombre,idCiudad) values('Cha�aral',8);
insert into ytp.comuna(nombre,idCiudad) values('Diego de Almagro',8);
insert into ytp.comuna(nombre,idCiudad) values('Caldera',9);
insert into ytp.comuna(nombre,idCiudad) values('Copiap�',9);
insert into ytp.comuna(nombre,idCiudad) values('Tierra Amarilla',9);
insert into ytp.comuna(nombre,idCiudad) values('Alto del Carmen',10);
insert into ytp.comuna(nombre,idCiudad) values('Freirina',10);
insert into ytp.comuna(nombre,idCiudad) values('Huasco',10);
insert into ytp.comuna(nombre,idCiudad) values('Vallenar',10);
insert into ytp.comuna(nombre,idCiudad) values('Canela',11);
insert into ytp.comuna(nombre,idCiudad) values('Illapel',11);
insert into ytp.comuna(nombre,idCiudad) values('Los Vilos',11);
insert into ytp.comuna(nombre,idCiudad) values('Salamanca',11);
insert into ytp.comuna(nombre,idCiudad) values('Andacollo',12);
insert into ytp.comuna(nombre,idCiudad) values('Coquimbo',12);
insert into ytp.comuna(nombre,idCiudad) values('La Higuera',12);
insert into ytp.comuna(nombre,idCiudad) values('La Serena',12);
insert into ytp.comuna(nombre,idCiudad) values('Paihuano',12);
insert into ytp.comuna(nombre,idCiudad) values('Vicu�a',12);
insert into ytp.comuna(nombre,idCiudad) values('Combarbal�',13);
insert into ytp.comuna(nombre,idCiudad) values('Monte Patria',13);
insert into ytp.comuna(nombre,idCiudad) values('Ovalle',13);
insert into ytp.comuna(nombre,idCiudad) values('Punitaqui',13);
insert into ytp.comuna(nombre,idCiudad) values('R�o Hurtado',13);
insert into ytp.comuna(nombre,idCiudad) values('Isla de Pascua',14);
insert into ytp.comuna(nombre,idCiudad) values('Calle Larga',15);
insert into ytp.comuna(nombre,idCiudad) values('Los Andes',15);
insert into ytp.comuna(nombre,idCiudad) values('Rinconada de Los Andes',15);
insert into ytp.comuna(nombre,idCiudad) values('San Esteban',15);
insert into ytp.comuna(nombre,idCiudad) values('Limache',16);
insert into ytp.comuna(nombre,idCiudad) values('Olmu�',16);
insert into ytp.comuna(nombre,idCiudad) values('Quilpu�',16);
insert into ytp.comuna(nombre,idCiudad) values('Villa Alemana',16);
insert into ytp.comuna(nombre,idCiudad) values('Cabildo',17);
insert into ytp.comuna(nombre,idCiudad) values('La Ligua',17);
insert into ytp.comuna(nombre,idCiudad) values('Papudo',17);
insert into ytp.comuna(nombre,idCiudad) values('Petorca',17);
insert into ytp.comuna(nombre,idCiudad) values('Zapallar',17);
insert into ytp.comuna(nombre,idCiudad) values('Hijuelas',18);
insert into ytp.comuna(nombre,idCiudad) values('La Calera',18);
insert into ytp.comuna(nombre,idCiudad) values('La Cruz',18);
insert into ytp.comuna(nombre,idCiudad) values('Nogales',18);
insert into ytp.comuna(nombre,idCiudad) values('Quillota',18);
insert into ytp.comuna(nombre,idCiudad) values('Algarrobo',19);
insert into ytp.comuna(nombre,idCiudad) values('Cartagena',19);
insert into ytp.comuna(nombre,idCiudad) values('El Quisco',19);
insert into ytp.comuna(nombre,idCiudad) values('El Tabo',19);
insert into ytp.comuna(nombre,idCiudad) values('San Antonio',19);
insert into ytp.comuna(nombre,idCiudad) values('Santo Domingo',19);
insert into ytp.comuna(nombre,idCiudad) values('Catemu',20);
insert into ytp.comuna(nombre,idCiudad) values('Llaillay',20);
insert into ytp.comuna(nombre,idCiudad) values('Panquehue',20);
insert into ytp.comuna(nombre,idCiudad) values('Putaendo',20);
insert into ytp.comuna(nombre,idCiudad) values('San Felipe',20);
insert into ytp.comuna(nombre,idCiudad) values('Santa Mar�a',20);
insert into ytp.comuna(nombre,idCiudad) values('Casablanca',21);
insert into ytp.comuna(nombre,idCiudad) values('Conc�n',21);
insert into ytp.comuna(nombre,idCiudad) values('Juan Fern�ndez',21);
insert into ytp.comuna(nombre,idCiudad) values('Puchuncav�',21);
insert into ytp.comuna(nombre,idCiudad) values('Quintero',21);
insert into ytp.comuna(nombre,idCiudad) values('Valpara�so',21);
insert into ytp.comuna(nombre,idCiudad) values('Vi�a del Mar',21);
insert into ytp.comuna(nombre,idCiudad) values('Codegua',22);
insert into ytp.comuna(nombre,idCiudad) values('Co�nco',22);
insert into ytp.comuna(nombre,idCiudad) values('Coltauco',22);
insert into ytp.comuna(nombre,idCiudad) values('Do�ihue',22);
insert into ytp.comuna(nombre,idCiudad) values('Graneros',22);
insert into ytp.comuna(nombre,idCiudad) values('Las Cabras',22);
insert into ytp.comuna(nombre,idCiudad) values('Machal�',22);
insert into ytp.comuna(nombre,idCiudad) values('Malloa',22);
insert into ytp.comuna(nombre,idCiudad) values('Olivar',22);
insert into ytp.comuna(nombre,idCiudad) values('Peumo',22);
insert into ytp.comuna(nombre,idCiudad) values('Pichidegua',22);
insert into ytp.comuna(nombre,idCiudad) values('Quinta de Tilcoco',22);
insert into ytp.comuna(nombre,idCiudad) values('Rancagua',22);
insert into ytp.comuna(nombre,idCiudad) values('Requ�noa',22);
insert into ytp.comuna(nombre,idCiudad) values('Rengo',22);
insert into ytp.comuna(nombre,idCiudad) values('San Francisco de Mostazal',22);
insert into ytp.comuna(nombre,idCiudad) values('San Vicente de Tagua Tagua',22);
insert into ytp.comuna(nombre,idCiudad) values('La Estrella',23);
insert into ytp.comuna(nombre,idCiudad) values('Litueche',23);
insert into ytp.comuna(nombre,idCiudad) values('Marchi�e',23);
insert into ytp.comuna(nombre,idCiudad) values('Navidad',23);
insert into ytp.comuna(nombre,idCiudad) values('Paredones',23);
insert into ytp.comuna(nombre,idCiudad) values('Pichilemu',23);
insert into ytp.comuna(nombre,idCiudad) values('Ch�pica',24);
insert into ytp.comuna(nombre,idCiudad) values('Chimbarongo',24);
insert into ytp.comuna(nombre,idCiudad) values('Lolol',24);
insert into ytp.comuna(nombre,idCiudad) values('Nancagua',24);
insert into ytp.comuna(nombre,idCiudad) values('Palmilla',24);
insert into ytp.comuna(nombre,idCiudad) values('Peralillo',24);
insert into ytp.comuna(nombre,idCiudad) values('Placilla',24);
insert into ytp.comuna(nombre,idCiudad) values('Pumanque',24);
insert into ytp.comuna(nombre,idCiudad) values('San Fernando',24);
insert into ytp.comuna(nombre,idCiudad) values('Santa Cruz',24);
insert into ytp.comuna(nombre,idCiudad) values('Cauquenes',25);
insert into ytp.comuna(nombre,idCiudad) values('Chanco',25);
insert into ytp.comuna(nombre,idCiudad) values('Pelluhue',25);
insert into ytp.comuna(nombre,idCiudad) values('Curic�',26);
insert into ytp.comuna(nombre,idCiudad) values('Huala��',26);
insert into ytp.comuna(nombre,idCiudad) values('Licant�n',26);
insert into ytp.comuna(nombre,idCiudad) values('Molina',26);
insert into ytp.comuna(nombre,idCiudad) values('Rauco',26);
insert into ytp.comuna(nombre,idCiudad) values('Romeral',26);
insert into ytp.comuna(nombre,idCiudad) values('Sagrada Familia',26);
insert into ytp.comuna(nombre,idCiudad) values('Teno',26);
insert into ytp.comuna(nombre,idCiudad) values('Vichuqu�n',26);
insert into ytp.comuna(nombre,idCiudad) values('Colb�n',27);
insert into ytp.comuna(nombre,idCiudad) values('Linares',27);
insert into ytp.comuna(nombre,idCiudad) values('Longav�',27);
insert into ytp.comuna(nombre,idCiudad) values('Parral',27);
insert into ytp.comuna(nombre,idCiudad) values('Retiro',27);
insert into ytp.comuna(nombre,idCiudad) values('San Javier de Loncomilla',27);
insert into ytp.comuna(nombre,idCiudad) values('Villa Alegre',27);
insert into ytp.comuna(nombre,idCiudad) values('Yerbas Buenas',27);
insert into ytp.comuna(nombre,idCiudad) values('Constituci�n',28);
insert into ytp.comuna(nombre,idCiudad) values('Curepto',28);
insert into ytp.comuna(nombre,idCiudad) values('Empedrado',28);
insert into ytp.comuna(nombre,idCiudad) values('Maule',28);
insert into ytp.comuna(nombre,idCiudad) values('Pelarco',28);
insert into ytp.comuna(nombre,idCiudad) values('Pencahue',28);
insert into ytp.comuna(nombre,idCiudad) values('R�o Claro',28);
insert into ytp.comuna(nombre,idCiudad) values('San Clemente',28);
insert into ytp.comuna(nombre,idCiudad) values('San Rafael',28);
insert into ytp.comuna(nombre,idCiudad) values('Talca',28);
insert into ytp.comuna(nombre,idCiudad) values('Arauco',29);
insert into ytp.comuna(nombre,idCiudad) values('Ca�ete',29);
insert into ytp.comuna(nombre,idCiudad) values('Contulmo',29);
insert into ytp.comuna(nombre,idCiudad) values('Curanilahue',29);
insert into ytp.comuna(nombre,idCiudad) values('Lebu',29);
insert into ytp.comuna(nombre,idCiudad) values('Los �lamos',29);
insert into ytp.comuna(nombre,idCiudad) values('Tir�a',29);
insert into ytp.comuna(nombre,idCiudad) values('Alto Biob�o',30);
insert into ytp.comuna(nombre,idCiudad) values('Antuco',30);
insert into ytp.comuna(nombre,idCiudad) values('Cabrero',30);
insert into ytp.comuna(nombre,idCiudad) values('Laja',30);
insert into ytp.comuna(nombre,idCiudad) values('Los �ngeles',30);
insert into ytp.comuna(nombre,idCiudad) values('Mulch�n',30);
insert into ytp.comuna(nombre,idCiudad) values('Nacimiento',30);
insert into ytp.comuna(nombre,idCiudad) values('Negrete',30);
insert into ytp.comuna(nombre,idCiudad) values('Quilaco',30);
insert into ytp.comuna(nombre,idCiudad) values('Quilleco',30);
insert into ytp.comuna(nombre,idCiudad) values('San Rosendo',30);
insert into ytp.comuna(nombre,idCiudad) values('Santa B�rbara',30);
insert into ytp.comuna(nombre,idCiudad) values('Tucapel',30);
insert into ytp.comuna(nombre,idCiudad) values('Yumbel',30);
insert into ytp.comuna(nombre,idCiudad) values('Chiguayante',31);
insert into ytp.comuna(nombre,idCiudad) values('Concepci�n',31);
insert into ytp.comuna(nombre,idCiudad) values('Coronel',31);
insert into ytp.comuna(nombre,idCiudad) values('Florida',31);
insert into ytp.comuna(nombre,idCiudad) values('Hualp�n',31);
insert into ytp.comuna(nombre,idCiudad) values('Hualqui',31);
insert into ytp.comuna(nombre,idCiudad) values('Lota',31);
insert into ytp.comuna(nombre,idCiudad) values('Penco',31);
insert into ytp.comuna(nombre,idCiudad) values('San Pedro de la Paz',31);
insert into ytp.comuna(nombre,idCiudad) values('Santa Juana',31);
insert into ytp.comuna(nombre,idCiudad) values('Talcahuano',31);
insert into ytp.comuna(nombre,idCiudad) values('Tom�',31);
insert into ytp.comuna(nombre,idCiudad) values('Bulnes',32);
insert into ytp.comuna(nombre,idCiudad) values('Chill�n',32);
insert into ytp.comuna(nombre,idCiudad) values('Chill�n Viejo',32);
insert into ytp.comuna(nombre,idCiudad) values('Cobquecura',32);
insert into ytp.comuna(nombre,idCiudad) values('Coelemu',32);
insert into ytp.comuna(nombre,idCiudad) values('Coihueco',32);
insert into ytp.comuna(nombre,idCiudad) values('El Carmen',32);
insert into ytp.comuna(nombre,idCiudad) values('Ninhue',32);
insert into ytp.comuna(nombre,idCiudad) values('�iqu�n',32);
insert into ytp.comuna(nombre,idCiudad) values('Pemuco',32);
insert into ytp.comuna(nombre,idCiudad) values('Pinto',32);
insert into ytp.comuna(nombre,idCiudad) values('Portezuelo',32);
insert into ytp.comuna(nombre,idCiudad) values('Quill�n',32);
insert into ytp.comuna(nombre,idCiudad) values('Quirihue',32);
insert into ytp.comuna(nombre,idCiudad) values('R�nquil',32);
insert into ytp.comuna(nombre,idCiudad) values('San Carlos',32);
insert into ytp.comuna(nombre,idCiudad) values('San Fabi�n',32);
insert into ytp.comuna(nombre,idCiudad) values('San Ignacio',32);
insert into ytp.comuna(nombre,idCiudad) values('San Nicol�s',32);
insert into ytp.comuna(nombre,idCiudad) values('Treguaco',32);
insert into ytp.comuna(nombre,idCiudad) values('Yungay',32);
insert into ytp.comuna(nombre,idCiudad) values('Carahue',33);
insert into ytp.comuna(nombre,idCiudad) values('Cholchol',33);
insert into ytp.comuna(nombre,idCiudad) values('Cunco',33);
insert into ytp.comuna(nombre,idCiudad) values('Curarrehue',33);
insert into ytp.comuna(nombre,idCiudad) values('Freire',33);
insert into ytp.comuna(nombre,idCiudad) values('Galvarino',33);
insert into ytp.comuna(nombre,idCiudad) values('Gorbea',33);
insert into ytp.comuna(nombre,idCiudad) values('Lautaro',33);
insert into ytp.comuna(nombre,idCiudad) values('Loncoche',33);
insert into ytp.comuna(nombre,idCiudad) values('Melipeuco',33);
insert into ytp.comuna(nombre,idCiudad) values('Nueva Imperial',33);
insert into ytp.comuna(nombre,idCiudad) values('Padre Las Casas',33);
insert into ytp.comuna(nombre,idCiudad) values('Perquenco',33);
insert into ytp.comuna(nombre,idCiudad) values('Pitrufqu�n',33);
insert into ytp.comuna(nombre,idCiudad) values('Puc�n',33);
insert into ytp.comuna(nombre,idCiudad) values('Saavedra',33);
insert into ytp.comuna(nombre,idCiudad) values('Temuco',33);
insert into ytp.comuna(nombre,idCiudad) values('Teodoro Schmidt',33);
insert into ytp.comuna(nombre,idCiudad) values('Tolt�n',33);
insert into ytp.comuna(nombre,idCiudad) values('Vilc�n',33);
insert into ytp.comuna(nombre,idCiudad) values('Villarrica',33);
insert into ytp.comuna(nombre,idCiudad) values('Angol',34);
insert into ytp.comuna(nombre,idCiudad) values('Collipulli',34);
insert into ytp.comuna(nombre,idCiudad) values('Curacaut�n',34);
insert into ytp.comuna(nombre,idCiudad) values('Ercilla',34);
insert into ytp.comuna(nombre,idCiudad) values('Lonquimay',34);
insert into ytp.comuna(nombre,idCiudad) values('Los Sauces',34);
insert into ytp.comuna(nombre,idCiudad) values('Lumaco',34);
insert into ytp.comuna(nombre,idCiudad) values('Pur�n',34);
insert into ytp.comuna(nombre,idCiudad) values('Renaico',34);
insert into ytp.comuna(nombre,idCiudad) values('Traigu�n',34);
insert into ytp.comuna(nombre,idCiudad) values('Victoria',34);
insert into ytp.comuna(nombre,idCiudad) values('Futrono',35);
insert into ytp.comuna(nombre,idCiudad) values('La Uni�n',35);
insert into ytp.comuna(nombre,idCiudad) values('Lago Ranco',35);
insert into ytp.comuna(nombre,idCiudad) values('R�o Bueno',35);
insert into ytp.comuna(nombre,idCiudad) values('Corral',36);
insert into ytp.comuna(nombre,idCiudad) values('Lanco',36);
insert into ytp.comuna(nombre,idCiudad) values('Los Lagos',36);
insert into ytp.comuna(nombre,idCiudad) values('M�fil',36);
insert into ytp.comuna(nombre,idCiudad) values('Mariquina',36);
insert into ytp.comuna(nombre,idCiudad) values('Paillaco',36);
insert into ytp.comuna(nombre,idCiudad) values('Panguipulli',36);
insert into ytp.comuna(nombre,idCiudad) values('Valdivia',36);
insert into ytp.comuna(nombre,idCiudad) values('Ancud',37);
insert into ytp.comuna(nombre,idCiudad) values('Castro',37);
insert into ytp.comuna(nombre,idCiudad) values('Chonchi',37);
insert into ytp.comuna(nombre,idCiudad) values('Curaco de V�lez',37);
insert into ytp.comuna(nombre,idCiudad) values('Dalcahue',37);
insert into ytp.comuna(nombre,idCiudad) values('Puqueld�n',37);
insert into ytp.comuna(nombre,idCiudad) values('Queil�n',37);
insert into ytp.comuna(nombre,idCiudad) values('Quell�n',37);
insert into ytp.comuna(nombre,idCiudad) values('Quemchi',37);
insert into ytp.comuna(nombre,idCiudad) values('Quinchao',37);
insert into ytp.comuna(nombre,idCiudad) values('Calbuco',38);
insert into ytp.comuna(nombre,idCiudad) values('Cocham�',38);
insert into ytp.comuna(nombre,idCiudad) values('Fresia',38);
insert into ytp.comuna(nombre,idCiudad) values('Frutillar',38);
insert into ytp.comuna(nombre,idCiudad) values('Llanquihue',38);
insert into ytp.comuna(nombre,idCiudad) values('Los Muermos',38);
insert into ytp.comuna(nombre,idCiudad) values('Maull�n',38);
insert into ytp.comuna(nombre,idCiudad) values('Puerto Montt',38);
insert into ytp.comuna(nombre,idCiudad) values('Puerto Varas',38);
insert into ytp.comuna(nombre,idCiudad) values('Osorno',39);
insert into ytp.comuna(nombre,idCiudad) values('Puerto Octay',39);
insert into ytp.comuna(nombre,idCiudad) values('Purranque',39);
insert into ytp.comuna(nombre,idCiudad) values('Puyehue',39);
insert into ytp.comuna(nombre,idCiudad) values('R�o Negro',39);
insert into ytp.comuna(nombre,idCiudad) values('San Pablo',39);
insert into ytp.comuna(nombre,idCiudad) values('San Juan de la Costa',39);
insert into ytp.comuna(nombre,idCiudad) values('Chait�n',40);
insert into ytp.comuna(nombre,idCiudad) values('Futaleuf�',40);
insert into ytp.comuna(nombre,idCiudad) values('Hualaihu�',40);
insert into ytp.comuna(nombre,idCiudad) values('Palena',40);
insert into ytp.comuna(nombre,idCiudad) values('Ays�n',41);
insert into ytp.comuna(nombre,idCiudad) values('Cisnes',41);
insert into ytp.comuna(nombre,idCiudad) values('Guaitecas',41);
insert into ytp.comuna(nombre,idCiudad) values('Cochrane',42);
insert into ytp.comuna(nombre,idCiudad) values('OHiggins',42);
insert into ytp.comuna(nombre,idCiudad) values('Tortel',42);
insert into ytp.comuna(nombre,idCiudad) values('Coyhaique',43);
insert into ytp.comuna(nombre,idCiudad) values('Lago Verde',43);
insert into ytp.comuna(nombre,idCiudad) values('Chile Chico',44);
insert into ytp.comuna(nombre,idCiudad) values('R�o Ib��ez',44);
insert into ytp.comuna(nombre,idCiudad) values('Ant�rtica',45);
insert into ytp.comuna(nombre,idCiudad) values('Cabo de Hornos',45);
insert into ytp.comuna(nombre,idCiudad) values('Laguna Blanca',46);
insert into ytp.comuna(nombre,idCiudad) values('Punta Arenas',46);
insert into ytp.comuna(nombre,idCiudad) values('R�o Verde',46);
insert into ytp.comuna(nombre,idCiudad) values('San Gregorio',46);
insert into ytp.comuna(nombre,idCiudad) values('Porvenir',47);
insert into ytp.comuna(nombre,idCiudad) values('Primavera',47);
insert into ytp.comuna(nombre,idCiudad) values('Timaukel',47);
insert into ytp.comuna(nombre,idCiudad) values('Natales',48);
insert into ytp.comuna(nombre,idCiudad) values('Torres del Paine',48);
insert into ytp.comuna(nombre,idCiudad) values('Colina',49);
insert into ytp.comuna(nombre,idCiudad) values('Lampa',49);
insert into ytp.comuna(nombre,idCiudad) values('Tiltil',49);
insert into ytp.comuna(nombre,idCiudad) values('Pirque',50);
insert into ytp.comuna(nombre,idCiudad) values('Puente Alto',50);
insert into ytp.comuna(nombre,idCiudad) values('San Jos� de Maipo',50);
insert into ytp.comuna(nombre,idCiudad) values('Buin',51);
insert into ytp.comuna(nombre,idCiudad) values('Calera de Tango',51);
insert into ytp.comuna(nombre,idCiudad) values('Paine',51);
insert into ytp.comuna(nombre,idCiudad) values('San Bernardo',51);
insert into ytp.comuna(nombre,idCiudad) values('Alhu�',52);
insert into ytp.comuna(nombre,idCiudad) values('Curacav�',52);
insert into ytp.comuna(nombre,idCiudad) values('Mar�a Pinto',52);
insert into ytp.comuna(nombre,idCiudad) values('Melipilla',52);
insert into ytp.comuna(nombre,idCiudad) values('San Pedro',52);
insert into ytp.comuna(nombre,idCiudad) values('Cerrillos',53);
insert into ytp.comuna(nombre,idCiudad) values('Cerro Navia',53);
insert into ytp.comuna(nombre,idCiudad) values('Conchal�',53);
insert into ytp.comuna(nombre,idCiudad) values('El Bosque',53);
insert into ytp.comuna(nombre,idCiudad) values('Estaci�n Central',53);
insert into ytp.comuna(nombre,idCiudad) values('Huechuraba',53);
insert into ytp.comuna(nombre,idCiudad) values('Independencia',53);
insert into ytp.comuna(nombre,idCiudad) values('La Cisterna',53);
insert into ytp.comuna(nombre,idCiudad) values('La Granja',53);
insert into ytp.comuna(nombre,idCiudad) values('La Florida',53);
insert into ytp.comuna(nombre,idCiudad) values('La Pintana',53);
insert into ytp.comuna(nombre,idCiudad) values('La Reina',53);
insert into ytp.comuna(nombre,idCiudad) values('Las Condes',53);
insert into ytp.comuna(nombre,idCiudad) values('Lo Barnechea',53);
insert into ytp.comuna(nombre,idCiudad) values('Lo Espejo',53);
insert into ytp.comuna(nombre,idCiudad) values('Lo Prado',53);
insert into ytp.comuna(nombre,idCiudad) values('Macul',53);
insert into ytp.comuna(nombre,idCiudad) values('Maip�',53);
insert into ytp.comuna(nombre,idCiudad) values('�u�oa',53);
insert into ytp.comuna(nombre,idCiudad) values('Pedro Aguirre Cerda',53);
insert into ytp.comuna(nombre,idCiudad) values('Pe�alol�n',53);
insert into ytp.comuna(nombre,idCiudad) values('Providencia',53);
insert into ytp.comuna(nombre,idCiudad) values('Pudahuel',53);
insert into ytp.comuna(nombre,idCiudad) values('Quilicura',53);
insert into ytp.comuna(nombre,idCiudad) values('Quinta Normal',53);
insert into ytp.comuna(nombre,idCiudad) values('Recoleta',53);
insert into ytp.comuna(nombre,idCiudad) values('Renca',53);
insert into ytp.comuna(nombre,idCiudad) values('San Miguel',53);
insert into ytp.comuna(nombre,idCiudad) values('San Joaqu�n',53);
insert into ytp.comuna(nombre,idCiudad) values('San Ram�n',53);
insert into ytp.comuna(nombre,idCiudad) values('Santiago',53);
insert into ytp.comuna(nombre,idCiudad) values('Vitacura',53);
insert into ytp.comuna(nombre,idCiudad) values('El Monte',54);
insert into ytp.comuna(nombre,idCiudad) values('Isla de Maipo',54);
insert into ytp.comuna(nombre,idCiudad) values('Padre Hurtado',54);
insert into ytp.comuna(nombre,idCiudad) values('Pe�aflor',54);
insert into ytp.comuna(nombre,idCiudad) values('Talagante',54);


INSERT INTO ytp.`categoria` VALUES (1,'retail'),(2,'otros');
INSERT INTO ytp.`pais` VALUES (1,'Chile');
INSERT INTO ytp.`ciudad` VALUES (1,'Arica',1),(2,'Putre',1),(3,'Iquique',1),(4,'Pozo Almonte',1),(5,'Antofagasta',1),(6,'Calama',1),(7,'Tocopilla',1),(8,'Cha�aral',1),(9,'Copiap�',1),(10,'Vallenar',1),(11,'Illapel',1),(12,'Coquimbo',1),(13,'Ovalle',1),(14,'Hanga Roa',1),(15,'Los Andes',1),(16,'Quilpu�',1),(17,'La Ligua',1),(18,'Quillota',1),(19,'San Antonio',1),(20,'San Felipe',1),(21,'Valpara�so',1),(22,'Rancagua',1),(23,'Pichilemu',1),(24,'San Fernando',1),(25,'Cauquenes',1),(26,'Curic�',1),(27,'Linares',1),(28,'Talca',1),(29,'Lebu',1),(30,'Los �ngeles',1),(31,'Concepci�n',1),(32,'Chill�n',1),(33,'Temuco',1),(34,'Angol',1),(35,'La Uni�n',1),(36,'Valdivia',1),(37,'Castro',1),(38,'Puerto Montt',1),(39,'Osorno',1),(40,'Chait�n',1),(41,'Puerto Ays�n',1),(42,'Cochrane',1),(43,'Coyhaique',1),(44,'Chile Chico',1),(45,'Puerto Williams',1),(46,'Punta Arenas',1),(47,'Porvenir',1),(48,'Puerto Natales',1),(49,'Colina',1),(50,'Puente Alto',1),(51,'San Bernardo',1),(52,'Melipilla',1),(53,'Santiago',1),(54,'Talagante',1);

INSERT INTO ytp.`comuna` VALUES (1,'Arica',1),(2,'Camarones',1),(3,'General Lagos',2),(4,'Putre',2),(5,'Alto Hospicio',3),(6,'Iquique',3),(7,'Cami�a',4),(8,'Colchane',4),(9,'Huara',4),(10,'Pica',4),(11,'Pozo Almonte',4),(12,'Antofagasta',5),(13,'Mejillones',5),(14,'Sierra Gorda',5),(15,'Taltal',5),(16,'Calama',6),(17,'Ollag�e',6),(18,'San Pedro de Atacama',6),(19,'Mar�a Elena',7),(20,'Tocopilla',7),(21,'Cha�aral',8),(22,'Diego de Almagro',8),(23,'Caldera',9),(24,'Copiap�',9),(25,'Tierra Amarilla',9),(26,'Alto del Carmen',10),(27,'Freirina',10),(28,'Huasco',10),(29,'Vallenar',10),(30,'Canela',11),(31,'Illapel',11),(32,'Los Vilos',11),(33,'Salamanca',11),(34,'Andacollo',12),(35,'Coquimbo',12),(36,'La Higuera',12),(37,'La Serena',12),(38,'Paihuano',12),(39,'Vicu�a',12),(40,'Combarbal�',13),(41,'Monte Patria',13),(42,'Ovalle',13),(43,'Punitaqui',13),(44,'R�o Hurtado',13),(45,'Isla de Pascua',14),(46,'Calle Larga',15),(47,'Los Andes',15),(48,'Rinconada de Los Andes',15),(49,'San Esteban',15),(50,'Limache',16),(51,'Olmu�',16),(52,'Quilpu�',16),(53,'Villa Alemana',16),(54,'Cabildo',17),(55,'La Ligua',17),(56,'Papudo',17),(57,'Petorca',17),(58,'Zapallar',17),(59,'Hijuelas',18),(60,'La Calera',18),(61,'La Cruz',18),(62,'Nogales',18),(63,'Quillota',18),(64,'Algarrobo',19),(65,'Cartagena',19),(66,'El Quisco',19),(67,'El Tabo',19),(68,'San Antonio',19),(69,'Santo Domingo',19),(70,'Catemu',20),(71,'Llaillay',20),(72,'Panquehue',20),(73,'Putaendo',20),(74,'San Felipe',20),(75,'Santa Mar�a',20),(76,'Casablanca',21),(77,'Conc�n',21),(78,'Juan Fern�ndez',21),(79,'Puchuncav�',21),(80,'Quintero',21),(81,'Valpara�so',21),(82,'Vi�a del Mar',21),(83,'Codegua',22),(84,'Co�nco',22),(85,'Coltauco',22),(86,'Do�ihue',22),(87,'Graneros',22),(88,'Las Cabras',22),(89,'Machal�',22),(90,'Malloa',22),(91,'Olivar',22),(92,'Peumo',22),(93,'Pichidegua',22),(94,'Quinta de Tilcoco',22),(95,'Rancagua',22),(96,'Requ�noa',22),(97,'Rengo',22),(98,'San Francisco de Mostazal',22),(99,'San Vicente de Tagua Tagua',22),(100,'La Estrella',23),(101,'Litueche',23),(102,'Marchi�e',23),(103,'Navidad',23),(104,'Paredones',23),(105,'Pichilemu',23),(106,'Ch�pica',24),(107,'Chimbarongo',24),(108,'Lolol',24),(109,'Nancagua',24),(110,'Palmilla',24),(111,'Peralillo',24),(112,'Placilla',24),(113,'Pumanque',24),(114,'San Fernando',24),(115,'Santa Cruz',24),(116,'Cauquenes',25),(117,'Chanco',25),(118,'Pelluhue',25),(119,'Curic�',26),(120,'Huala��',26),(121,'Licant�n',26),(122,'Molina',26),(123,'Rauco',26),(124,'Romeral',26),(125,'Sagrada Familia',26),(126,'Teno',26),(127,'Vichuqu�n',26),(128,'Colb�n',27),(129,'Linares',27),(130,'Longav�',27),(131,'Parral',27),(132,'Retiro',27),(133,'San Javier de Loncomilla',27),(134,'Villa Alegre',27),(135,'Yerbas Buenas',27),(136,'Constituci�n',28),(137,'Curepto',28),(138,'Empedrado',28),(139,'Maule',28),(140,'Pelarco',28),(141,'Pencahue',28),(142,'R�o Claro',28),(143,'San Clemente',28),(144,'San Rafael',28),(145,'Talca',28),(146,'Arauco',29),(147,'Ca�ete',29),(148,'Contulmo',29),(149,'Curanilahue',29),(150,'Lebu',29),(151,'Los �lamos',29),(152,'Tir�a',29),(153,'Alto Biob�o',30),(154,'Antuco',30),(155,'Cabrero',30),(156,'Laja',30),(157,'Los �ngeles',30),(158,'Mulch�n',30),(159,'Nacimiento',30),(160,'Negrete',30),(161,'Quilaco',30),(162,'Quilleco',30),(163,'San Rosendo',30),(164,'Santa B�rbara',30),(165,'Tucapel',30),(166,'Yumbel',30),(167,'Chiguayante',31),(168,'Concepci�n',31),(169,'Coronel',31),(170,'Florida',31),(171,'Hualp�n',31),(172,'Hualqui',31),(173,'Lota',31),(174,'Penco',31),(175,'San Pedro de la Paz',31),(176,'Santa Juana',31),(177,'Talcahuano',31),(178,'Tom�',31),(179,'Bulnes',32),(180,'Chill�n',32),(181,'Chill�n Viejo',32),(182,'Cobquecura',32),(183,'Coelemu',32),(184,'Coihueco',32),(185,'El Carmen',32),(186,'Ninhue',32),(187,'�iqu�n',32),(188,'Pemuco',32),(189,'Pinto',32),(190,'Portezuelo',32),(191,'Quill�n',32),(192,'Quirihue',32),(193,'R�nquil',32),(194,'San Carlos',32),(195,'San Fabi�n',32),(196,'San Ignacio',32),(197,'San Nicol�s',32),(198,'Treguaco',32),(199,'Yungay',32),(200,'Carahue',33),(201,'Cholchol',33),(202,'Cunco',33),(203,'Curarrehue',33),(204,'Freire',33),(205,'Galvarino',33),(206,'Gorbea',33),(207,'Lautaro',33),(208,'Loncoche',33),(209,'Melipeuco',33),(210,'Nueva Imperial',33),(211,'Padre Las Casas',33),(212,'Perquenco',33),(213,'Pitrufqu�n',33),(214,'Puc�n',33),(215,'Saavedra',33),(216,'Temuco',33),(217,'Teodoro Schmidt',33),(218,'Tolt�n',33),(219,'Vilc�n',33),(220,'Villarrica',33),(221,'Angol',34),(222,'Collipulli',34),(223,'Curacaut�n',34),(224,'Ercilla',34),(225,'Lonquimay',34),(226,'Los Sauces',34),(227,'Lumaco',34),(228,'Pur�n',34),(229,'Renaico',34),(230,'Traigu�n',34),(231,'Victoria',34),(232,'Futrono',35),(233,'La Uni�n',35),(234,'Lago Ranco',35),(235,'R�o Bueno',35),(236,'Corral',36),(237,'Lanco',36),(238,'Los Lagos',36),(239,'M�fil',36),(240,'Mariquina',36),(241,'Paillaco',36),(242,'Panguipulli',36),(243,'Valdivia',36),(244,'Ancud',37),(245,'Castro',37),(246,'Chonchi',37),(247,'Curaco de V�lez',37),(248,'Dalcahue',37),(249,'Puqueld�n',37),(250,'Queil�n',37),(251,'Quell�n',37),(252,'Quemchi',37),(253,'Quinchao',37),(254,'Calbuco',38),(255,'Cocham�',38),(256,'Fresia',38),(257,'Frutillar',38),(258,'Llanquihue',38),(259,'Los Muermos',38),(260,'Maull�n',38),(261,'Puerto Montt',38),(262,'Puerto Varas',38),(263,'Osorno',39),(264,'Puerto Octay',39),(265,'Purranque',39),(266,'Puyehue',39),(267,'R�o Negro',39),(268,'San Pablo',39),(269,'San Juan de la Costa',39),(270,'Chait�n',40),(271,'Futaleuf�',40),(272,'Hualaihu�',40),(273,'Palena',40),(274,'Ays�n',41),(275,'Cisnes',41),(276,'Guaitecas',41),(277,'Cochrane',42),(278,'OHiggins',42),(279,'Tortel',42),(280,'Coyhaique',43),(281,'Lago Verde',43),(282,'Chile Chico',44),(283,'R�o Ib��ez',44),(284,'Ant�rtica',45),(285,'Cabo de Hornos',45),(286,'Laguna Blanca',46),(287,'Punta Arenas',46),(288,'R�o Verde',46),(289,'San Gregorio',46),(290,'Porvenir',47),(291,'Primavera',47),(292,'Timaukel',47),(293,'Natales',48),(294,'Torres del Paine',48),(295,'Colina',49),(296,'Lampa',49),(297,'Tiltil',49),(298,'Pirque',50),(299,'Puente Alto',50),(300,'San Jos� de Maipo',50),(301,'Buin',51),(302,'Calera de Tango',51),(303,'Paine',51),(304,'San Bernardo',51),(305,'Alhu�',52),(306,'Curacav�',52),(307,'Mar�a Pinto',52),(308,'Melipilla',52),(309,'San Pedro',52),(310,'Cerrillos',53),(311,'Cerro Navia',53),(312,'Conchal�',53),(313,'El Bosque',53),(314,'Estaci�n Central',53),(315,'Huechuraba',53),(316,'Independencia',53),(317,'La Cisterna',53),(318,'La Granja',53),(319,'La Florida',53),(320,'La Pintana',53),(321,'La Reina',53),(322,'Las Condes',53),(323,'Lo Barnechea',53),(324,'Lo Espejo',53),(325,'Lo Prado',53),(326,'Macul',53),(327,'Maip�',53),(328,'�u�oa',53),(329,'Pedro Aguirre Cerda',53),(330,'Pe�alol�n',53),(331,'Providencia',53),(332,'Pudahuel',53),(333,'Quilicura',53),(334,'Quinta Normal',53),(335,'Recoleta',53),(336,'Renca',53),(337,'San Miguel',53),(338,'San Joaqu�n',53),(339,'San Ram�n',53),(340,'Santiago',53),(341,'Vitacura',53),(342,'El Monte',54),(343,'Isla de Maipo',54),(344,'Padre Hurtado',54),(345,'Pe�aflor',54),(346,'Talagante',54);


INSERT INTO ytp.`tipo_usuario` VALUES (1,'administrador'),(2,'usuario'),(3,'empresa'),(4,'particular');
INSERT INTO ytp.`users` VALUES (1,1,'2','te',NULL,NULL,'te@te.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$qheQ3Dwi5srDMsXr5RXAC.2oVmIuP4FjA0RhD6WTN27j//U5LrYJi','92544c7a36db069c54e8844fe208f78a4d377d45'),(2,2,'1','Felipe',NULL,NULL,'fhernandez@hyh.cl',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$YiufdN5xP590c1wHBVkTHuwT21vXg6WX24yhV24kFzsT/f4AtGgcO','21aacbef1163d21ec42e32ae9ec314496b7004ba'),(3,2,'3','3',NULL,NULL,'3@3.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$MmqXs1KyA2iKcaHqEMcfwuhOK/gpHvSil2eb38l1VWAo1Z8qlHskG','f91b90c815b339b675807c75cde7b22207f1851a'),(7,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(8,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(9,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(10,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(11,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(12,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(13,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(14,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(15,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(16,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(17,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(18,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(19,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(20,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(21,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(22,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(23,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(24,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(25,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(26,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(27,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(28,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(29,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f'),(30,2,'7','qwe',NULL,NULL,'1@1.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'$2a$10$LAQJSnSfqlRbohCuE2yue.aHQp8dejEMYxWBh8PxtvMeT9HDBpgCy','75c1bc52d3155f560656a28322b9c890cad6306f');
