insert into ytp.tipo_usuario(tipo) values('administrador');
insert into ytp.tipo_usuario(tipo) values('usuario');
insert into ytp.tipo_usuario(tipo) values('empresa');
insert into ytp.tipo_usuario(tipo) values('particular');

insert into ytp.categoria(nombre) values('retail');
insert into ytp.categoria(nombre) values('otros');

insert into ytp.pais(nombre) values('Chile');

insert into ytp.ciudad(nombre,idPais) values('Arica',1);
insert into ytp.ciudad(nombre,idPais) values('Putre',1);
insert into ytp.ciudad(nombre,idPais) values('Iquique',1);
insert into ytp.ciudad(nombre,idPais) values('Pozo Almonte',1);
insert into ytp.ciudad(nombre,idPais) values('Antofagasta',1);
insert into ytp.ciudad(nombre,idPais) values('Calama',1);
insert into ytp.ciudad(nombre,idPais) values('Tocopilla',1);
insert into ytp.ciudad(nombre,idPais) values('Chañaral',1);
insert into ytp.ciudad(nombre,idPais) values('Copiapó',1);
insert into ytp.ciudad(nombre,idPais) values('Vallenar',1);
insert into ytp.ciudad(nombre,idPais) values('Illapel',1);
insert into ytp.ciudad(nombre,idPais) values('Coquimbo',1);
insert into ytp.ciudad(nombre,idPais) values('Ovalle',1);
insert into ytp.ciudad(nombre,idPais) values('Hanga Roa',1);
insert into ytp.ciudad(nombre,idPais) values('Los Andes',1);
insert into ytp.ciudad(nombre,idPais) values('Quilpué',1);
insert into ytp.ciudad(nombre,idPais) values('La Ligua',1);
insert into ytp.ciudad(nombre,idPais) values('Quillota',1);
insert into ytp.ciudad(nombre,idPais) values('San Antonio',1);
insert into ytp.ciudad(nombre,idPais) values('San Felipe',1);
insert into ytp.ciudad(nombre,idPais) values('Valparaíso',1);
insert into ytp.ciudad(nombre,idPais) values('Rancagua',1);
insert into ytp.ciudad(nombre,idPais) values('Pichilemu',1);
insert into ytp.ciudad(nombre,idPais) values('San Fernando',1);
insert into ytp.ciudad(nombre,idPais) values('Cauquenes',1);
insert into ytp.ciudad(nombre,idPais) values('Curicó',1);
insert into ytp.ciudad(nombre,idPais) values('Linares',1);
insert into ytp.ciudad(nombre,idPais) values('Talca',1);
insert into ytp.ciudad(nombre,idPais) values('Lebu',1);
insert into ytp.ciudad(nombre,idPais) values('Los Ángeles',1);
insert into ytp.ciudad(nombre,idPais) values('Concepción',1);
insert into ytp.ciudad(nombre,idPais) values('Chillán',1);
insert into ytp.ciudad(nombre,idPais) values('Temuco',1);
insert into ytp.ciudad(nombre,idPais) values('Angol',1);
insert into ytp.ciudad(nombre,idPais) values('La Unión',1);
insert into ytp.ciudad(nombre,idPais) values('Valdivia',1);
insert into ytp.ciudad(nombre,idPais) values('Castro',1);
insert into ytp.ciudad(nombre,idPais) values('Puerto Montt',1);
insert into ytp.ciudad(nombre,idPais) values('Osorno',1);
insert into ytp.ciudad(nombre,idPais) values('Chaitén',1);
insert into ytp.ciudad(nombre,idPais) values('Puerto Aysén',1);
insert into ytp.ciudad(nombre,idPais) values('Cochrane',1);
insert into ytp.ciudad(nombre,idPais) values('Coyhaique',1);
insert into ytp.ciudad(nombre,idPais) values('Chile Chico',1);
insert into ytp.ciudad(nombre,idPais) values('Puerto Williams',1);
insert into ytp.ciudad(nombre,idPais) values('Punta Arenas',1);
insert into ytp.ciudad(nombre,idPais) values('Porvenir',1);
insert into ytp.ciudad(nombre,idPais) values('Puerto Natales',1);
insert into ytp.ciudad(nombre,idPais) values('Colina',1);
insert into ytp.ciudad(nombre,idPais) values('Puente Alto',1);
insert into ytp.ciudad(nombre,idPais) values('San Bernardo',1);
insert into ytp.ciudad(nombre,idPais) values('Melipilla',1);
insert into ytp.ciudad(nombre,idPais) values('Santiago',1);
insert into ytp.ciudad(nombre,idPais) values('Talagante',1);

insert into ytp.comuna(nombre,idCiudad) values('Arica',1);
insert into ytp.comuna(nombre,idCiudad) values('Camarones',1);
insert into ytp.comuna(nombre,idCiudad) values('General Lagos',2);
insert into ytp.comuna(nombre,idCiudad) values('Putre',2);
insert into ytp.comuna(nombre,idCiudad) values('Alto Hospicio',3);
insert into ytp.comuna(nombre,idCiudad) values('Iquique',3);
insert into ytp.comuna(nombre,idCiudad) values('Camiña',4);
insert into ytp.comuna(nombre,idCiudad) values('Colchane',4);
insert into ytp.comuna(nombre,idCiudad) values('Huara',4);
insert into ytp.comuna(nombre,idCiudad) values('Pica',4);
insert into ytp.comuna(nombre,idCiudad) values('Pozo Almonte',4);
insert into ytp.comuna(nombre,idCiudad) values('Antofagasta',5);
insert into ytp.comuna(nombre,idCiudad) values('Mejillones',5);
insert into ytp.comuna(nombre,idCiudad) values('Sierra Gorda',5);
insert into ytp.comuna(nombre,idCiudad) values('Taltal',5);
insert into ytp.comuna(nombre,idCiudad) values('Calama',6);
insert into ytp.comuna(nombre,idCiudad) values('Ollagüe',6);
insert into ytp.comuna(nombre,idCiudad) values('San Pedro de Atacama',6);
insert into ytp.comuna(nombre,idCiudad) values('María Elena',7);
insert into ytp.comuna(nombre,idCiudad) values('Tocopilla',7);
insert into ytp.comuna(nombre,idCiudad) values('Chañaral',8);
insert into ytp.comuna(nombre,idCiudad) values('Diego de Almagro',8);
insert into ytp.comuna(nombre,idCiudad) values('Caldera',9);
insert into ytp.comuna(nombre,idCiudad) values('Copiapó',9);
insert into ytp.comuna(nombre,idCiudad) values('Tierra Amarilla',9);
insert into ytp.comuna(nombre,idCiudad) values('Alto del Carmen',10);
insert into ytp.comuna(nombre,idCiudad) values('Freirina',10);
insert into ytp.comuna(nombre,idCiudad) values('Huasco',10);
insert into ytp.comuna(nombre,idCiudad) values('Vallenar',10);
insert into ytp.comuna(nombre,idCiudad) values('Canela',11);
insert into ytp.comuna(nombre,idCiudad) values('Illapel',11);
insert into ytp.comuna(nombre,idCiudad) values('Los Vilos',11);
insert into ytp.comuna(nombre,idCiudad) values('Salamanca',11);
insert into ytp.comuna(nombre,idCiudad) values('Andacollo',12);
insert into ytp.comuna(nombre,idCiudad) values('Coquimbo',12);
insert into ytp.comuna(nombre,idCiudad) values('La Higuera',12);
insert into ytp.comuna(nombre,idCiudad) values('La Serena',12);
insert into ytp.comuna(nombre,idCiudad) values('Paihuano',12);
insert into ytp.comuna(nombre,idCiudad) values('Vicuña',12);
insert into ytp.comuna(nombre,idCiudad) values('Combarbalá',13);
insert into ytp.comuna(nombre,idCiudad) values('Monte Patria',13);
insert into ytp.comuna(nombre,idCiudad) values('Ovalle',13);
insert into ytp.comuna(nombre,idCiudad) values('Punitaqui',13);
insert into ytp.comuna(nombre,idCiudad) values('Río Hurtado',13);
insert into ytp.comuna(nombre,idCiudad) values('Isla de Pascua',14);
insert into ytp.comuna(nombre,idCiudad) values('Calle Larga',15);
insert into ytp.comuna(nombre,idCiudad) values('Los Andes',15);
insert into ytp.comuna(nombre,idCiudad) values('Rinconada de Los Andes',15);
insert into ytp.comuna(nombre,idCiudad) values('San Esteban',15);
insert into ytp.comuna(nombre,idCiudad) values('Limache',16);
insert into ytp.comuna(nombre,idCiudad) values('Olmué',16);
insert into ytp.comuna(nombre,idCiudad) values('Quilpué',16);
insert into ytp.comuna(nombre,idCiudad) values('Villa Alemana',16);
insert into ytp.comuna(nombre,idCiudad) values('Cabildo',17);
insert into ytp.comuna(nombre,idCiudad) values('La Ligua',17);
insert into ytp.comuna(nombre,idCiudad) values('Papudo',17);
insert into ytp.comuna(nombre,idCiudad) values('Petorca',17);
insert into ytp.comuna(nombre,idCiudad) values('Zapallar',17);
insert into ytp.comuna(nombre,idCiudad) values('Hijuelas',18);
insert into ytp.comuna(nombre,idCiudad) values('La Calera',18);
insert into ytp.comuna(nombre,idCiudad) values('La Cruz',18);
insert into ytp.comuna(nombre,idCiudad) values('Nogales',18);
insert into ytp.comuna(nombre,idCiudad) values('Quillota',18);
insert into ytp.comuna(nombre,idCiudad) values('Algarrobo',19);
insert into ytp.comuna(nombre,idCiudad) values('Cartagena',19);
insert into ytp.comuna(nombre,idCiudad) values('El Quisco',19);
insert into ytp.comuna(nombre,idCiudad) values('El Tabo',19);
insert into ytp.comuna(nombre,idCiudad) values('San Antonio',19);
insert into ytp.comuna(nombre,idCiudad) values('Santo Domingo',19);
insert into ytp.comuna(nombre,idCiudad) values('Catemu',20);
insert into ytp.comuna(nombre,idCiudad) values('Llaillay',20);
insert into ytp.comuna(nombre,idCiudad) values('Panquehue',20);
insert into ytp.comuna(nombre,idCiudad) values('Putaendo',20);
insert into ytp.comuna(nombre,idCiudad) values('San Felipe',20);
insert into ytp.comuna(nombre,idCiudad) values('Santa María',20);
insert into ytp.comuna(nombre,idCiudad) values('Casablanca',21);
insert into ytp.comuna(nombre,idCiudad) values('Concón',21);
insert into ytp.comuna(nombre,idCiudad) values('Juan Fernández',21);
insert into ytp.comuna(nombre,idCiudad) values('Puchuncaví',21);
insert into ytp.comuna(nombre,idCiudad) values('Quintero',21);
insert into ytp.comuna(nombre,idCiudad) values('Valparaíso',21);
insert into ytp.comuna(nombre,idCiudad) values('Viña del Mar',21);
insert into ytp.comuna(nombre,idCiudad) values('Codegua',22);
insert into ytp.comuna(nombre,idCiudad) values('Coínco',22);
insert into ytp.comuna(nombre,idCiudad) values('Coltauco',22);
insert into ytp.comuna(nombre,idCiudad) values('Doñihue',22);
insert into ytp.comuna(nombre,idCiudad) values('Graneros',22);
insert into ytp.comuna(nombre,idCiudad) values('Las Cabras',22);
insert into ytp.comuna(nombre,idCiudad) values('Machalí',22);
insert into ytp.comuna(nombre,idCiudad) values('Malloa',22);
insert into ytp.comuna(nombre,idCiudad) values('Olivar',22);
insert into ytp.comuna(nombre,idCiudad) values('Peumo',22);
insert into ytp.comuna(nombre,idCiudad) values('Pichidegua',22);
insert into ytp.comuna(nombre,idCiudad) values('Quinta de Tilcoco',22);
insert into ytp.comuna(nombre,idCiudad) values('Rancagua',22);
insert into ytp.comuna(nombre,idCiudad) values('Requínoa',22);
insert into ytp.comuna(nombre,idCiudad) values('Rengo',22);
insert into ytp.comuna(nombre,idCiudad) values('San Francisco de Mostazal',22);
insert into ytp.comuna(nombre,idCiudad) values('San Vicente de Tagua Tagua',22);
insert into ytp.comuna(nombre,idCiudad) values('La Estrella',23);
insert into ytp.comuna(nombre,idCiudad) values('Litueche',23);
insert into ytp.comuna(nombre,idCiudad) values('Marchiüe',23);
insert into ytp.comuna(nombre,idCiudad) values('Navidad',23);
insert into ytp.comuna(nombre,idCiudad) values('Paredones',23);
insert into ytp.comuna(nombre,idCiudad) values('Pichilemu',23);
insert into ytp.comuna(nombre,idCiudad) values('Chépica',24);
insert into ytp.comuna(nombre,idCiudad) values('Chimbarongo',24);
insert into ytp.comuna(nombre,idCiudad) values('Lolol',24);
insert into ytp.comuna(nombre,idCiudad) values('Nancagua',24);
insert into ytp.comuna(nombre,idCiudad) values('Palmilla',24);
insert into ytp.comuna(nombre,idCiudad) values('Peralillo',24);
insert into ytp.comuna(nombre,idCiudad) values('Placilla',24);
insert into ytp.comuna(nombre,idCiudad) values('Pumanque',24);
insert into ytp.comuna(nombre,idCiudad) values('San Fernando',24);
insert into ytp.comuna(nombre,idCiudad) values('Santa Cruz',24);
insert into ytp.comuna(nombre,idCiudad) values('Cauquenes',25);
insert into ytp.comuna(nombre,idCiudad) values('Chanco',25);
insert into ytp.comuna(nombre,idCiudad) values('Pelluhue',25);
insert into ytp.comuna(nombre,idCiudad) values('Curicó',26);
insert into ytp.comuna(nombre,idCiudad) values('Hualañé',26);
insert into ytp.comuna(nombre,idCiudad) values('Licantán',26);
insert into ytp.comuna(nombre,idCiudad) values('Molina',26);
insert into ytp.comuna(nombre,idCiudad) values('Rauco',26);
insert into ytp.comuna(nombre,idCiudad) values('Romeral',26);
insert into ytp.comuna(nombre,idCiudad) values('Sagrada Familia',26);
insert into ytp.comuna(nombre,idCiudad) values('Teno',26);
insert into ytp.comuna(nombre,idCiudad) values('Vichuquén',26);
insert into ytp.comuna(nombre,idCiudad) values('Colbún',27);
insert into ytp.comuna(nombre,idCiudad) values('Linares',27);
insert into ytp.comuna(nombre,idCiudad) values('Longaví',27);
insert into ytp.comuna(nombre,idCiudad) values('Parral',27);
insert into ytp.comuna(nombre,idCiudad) values('Retiro',27);
insert into ytp.comuna(nombre,idCiudad) values('San Javier de Loncomilla',27);
insert into ytp.comuna(nombre,idCiudad) values('Villa Alegre',27);
insert into ytp.comuna(nombre,idCiudad) values('Yerbas Buenas',27);
insert into ytp.comuna(nombre,idCiudad) values('Constitución',28);
insert into ytp.comuna(nombre,idCiudad) values('Curepto',28);
insert into ytp.comuna(nombre,idCiudad) values('Empedrado',28);
insert into ytp.comuna(nombre,idCiudad) values('Maule',28);
insert into ytp.comuna(nombre,idCiudad) values('Pelarco',28);
insert into ytp.comuna(nombre,idCiudad) values('Pencahue',28);
insert into ytp.comuna(nombre,idCiudad) values('Río Claro',28);
insert into ytp.comuna(nombre,idCiudad) values('San Clemente',28);
insert into ytp.comuna(nombre,idCiudad) values('San Rafael',28);
insert into ytp.comuna(nombre,idCiudad) values('Talca',28);
insert into ytp.comuna(nombre,idCiudad) values('Arauco',29);
insert into ytp.comuna(nombre,idCiudad) values('Cañete',29);
insert into ytp.comuna(nombre,idCiudad) values('Contulmo',29);
insert into ytp.comuna(nombre,idCiudad) values('Curanilahue',29);
insert into ytp.comuna(nombre,idCiudad) values('Lebu',29);
insert into ytp.comuna(nombre,idCiudad) values('Los Álamos',29);
insert into ytp.comuna(nombre,idCiudad) values('Tirúa',29);
insert into ytp.comuna(nombre,idCiudad) values('Alto Biobío',30);
insert into ytp.comuna(nombre,idCiudad) values('Antuco',30);
insert into ytp.comuna(nombre,idCiudad) values('Cabrero',30);
insert into ytp.comuna(nombre,idCiudad) values('Laja',30);
insert into ytp.comuna(nombre,idCiudad) values('Los Ángeles',30);
insert into ytp.comuna(nombre,idCiudad) values('Mulchén',30);
insert into ytp.comuna(nombre,idCiudad) values('Nacimiento',30);
insert into ytp.comuna(nombre,idCiudad) values('Negrete',30);
insert into ytp.comuna(nombre,idCiudad) values('Quilaco',30);
insert into ytp.comuna(nombre,idCiudad) values('Quilleco',30);
insert into ytp.comuna(nombre,idCiudad) values('San Rosendo',30);
insert into ytp.comuna(nombre,idCiudad) values('Santa Bárbara',30);
insert into ytp.comuna(nombre,idCiudad) values('Tucapel',30);
insert into ytp.comuna(nombre,idCiudad) values('Yumbel',30);
insert into ytp.comuna(nombre,idCiudad) values('Chiguayante',31);
insert into ytp.comuna(nombre,idCiudad) values('Concepción',31);
insert into ytp.comuna(nombre,idCiudad) values('Coronel',31);
insert into ytp.comuna(nombre,idCiudad) values('Florida',31);
insert into ytp.comuna(nombre,idCiudad) values('Hualpén',31);
insert into ytp.comuna(nombre,idCiudad) values('Hualqui',31);
insert into ytp.comuna(nombre,idCiudad) values('Lota',31);
insert into ytp.comuna(nombre,idCiudad) values('Penco',31);
insert into ytp.comuna(nombre,idCiudad) values('San Pedro de la Paz',31);
insert into ytp.comuna(nombre,idCiudad) values('Santa Juana',31);
insert into ytp.comuna(nombre,idCiudad) values('Talcahuano',31);
insert into ytp.comuna(nombre,idCiudad) values('Tomé',31);
insert into ytp.comuna(nombre,idCiudad) values('Bulnes',32);
insert into ytp.comuna(nombre,idCiudad) values('Chillán',32);
insert into ytp.comuna(nombre,idCiudad) values('Chillán Viejo',32);
insert into ytp.comuna(nombre,idCiudad) values('Cobquecura',32);
insert into ytp.comuna(nombre,idCiudad) values('Coelemu',32);
insert into ytp.comuna(nombre,idCiudad) values('Coihueco',32);
insert into ytp.comuna(nombre,idCiudad) values('El Carmen',32);
insert into ytp.comuna(nombre,idCiudad) values('Ninhue',32);
insert into ytp.comuna(nombre,idCiudad) values('Ñiquén',32);
insert into ytp.comuna(nombre,idCiudad) values('Pemuco',32);
insert into ytp.comuna(nombre,idCiudad) values('Pinto',32);
insert into ytp.comuna(nombre,idCiudad) values('Portezuelo',32);
insert into ytp.comuna(nombre,idCiudad) values('Quillón',32);
insert into ytp.comuna(nombre,idCiudad) values('Quirihue',32);
insert into ytp.comuna(nombre,idCiudad) values('Ránquil',32);
insert into ytp.comuna(nombre,idCiudad) values('San Carlos',32);
insert into ytp.comuna(nombre,idCiudad) values('San Fabián',32);
insert into ytp.comuna(nombre,idCiudad) values('San Ignacio',32);
insert into ytp.comuna(nombre,idCiudad) values('San Nicolás',32);
insert into ytp.comuna(nombre,idCiudad) values('Treguaco',32);
insert into ytp.comuna(nombre,idCiudad) values('Yungay',32);
insert into ytp.comuna(nombre,idCiudad) values('Carahue',33);
insert into ytp.comuna(nombre,idCiudad) values('Cholchol',33);
insert into ytp.comuna(nombre,idCiudad) values('Cunco',33);
insert into ytp.comuna(nombre,idCiudad) values('Curarrehue',33);
insert into ytp.comuna(nombre,idCiudad) values('Freire',33);
insert into ytp.comuna(nombre,idCiudad) values('Galvarino',33);
insert into ytp.comuna(nombre,idCiudad) values('Gorbea',33);
insert into ytp.comuna(nombre,idCiudad) values('Lautaro',33);
insert into ytp.comuna(nombre,idCiudad) values('Loncoche',33);
insert into ytp.comuna(nombre,idCiudad) values('Melipeuco',33);
insert into ytp.comuna(nombre,idCiudad) values('Nueva Imperial',33);
insert into ytp.comuna(nombre,idCiudad) values('Padre Las Casas',33);
insert into ytp.comuna(nombre,idCiudad) values('Perquenco',33);
insert into ytp.comuna(nombre,idCiudad) values('Pitrufquén',33);
insert into ytp.comuna(nombre,idCiudad) values('Pucón',33);
insert into ytp.comuna(nombre,idCiudad) values('Saavedra',33);
insert into ytp.comuna(nombre,idCiudad) values('Temuco',33);
insert into ytp.comuna(nombre,idCiudad) values('Teodoro Schmidt',33);
insert into ytp.comuna(nombre,idCiudad) values('Toltén',33);
insert into ytp.comuna(nombre,idCiudad) values('Vilcún',33);
insert into ytp.comuna(nombre,idCiudad) values('Villarrica',33);
insert into ytp.comuna(nombre,idCiudad) values('Angol',34);
insert into ytp.comuna(nombre,idCiudad) values('Collipulli',34);
insert into ytp.comuna(nombre,idCiudad) values('Curacautín',34);
insert into ytp.comuna(nombre,idCiudad) values('Ercilla',34);
insert into ytp.comuna(nombre,idCiudad) values('Lonquimay',34);
insert into ytp.comuna(nombre,idCiudad) values('Los Sauces',34);
insert into ytp.comuna(nombre,idCiudad) values('Lumaco',34);
insert into ytp.comuna(nombre,idCiudad) values('Purén',34);
insert into ytp.comuna(nombre,idCiudad) values('Renaico',34);
insert into ytp.comuna(nombre,idCiudad) values('Traiguén',34);
insert into ytp.comuna(nombre,idCiudad) values('Victoria',34);
insert into ytp.comuna(nombre,idCiudad) values('Futrono',35);
insert into ytp.comuna(nombre,idCiudad) values('La Unión',35);
insert into ytp.comuna(nombre,idCiudad) values('Lago Ranco',35);
insert into ytp.comuna(nombre,idCiudad) values('Río Bueno',35);
insert into ytp.comuna(nombre,idCiudad) values('Corral',36);
insert into ytp.comuna(nombre,idCiudad) values('Lanco',36);
insert into ytp.comuna(nombre,idCiudad) values('Los Lagos',36);
insert into ytp.comuna(nombre,idCiudad) values('Máfil',36);
insert into ytp.comuna(nombre,idCiudad) values('Mariquina',36);
insert into ytp.comuna(nombre,idCiudad) values('Paillaco',36);
insert into ytp.comuna(nombre,idCiudad) values('Panguipulli',36);
insert into ytp.comuna(nombre,idCiudad) values('Valdivia',36);
insert into ytp.comuna(nombre,idCiudad) values('Ancud',37);
insert into ytp.comuna(nombre,idCiudad) values('Castro',37);
insert into ytp.comuna(nombre,idCiudad) values('Chonchi',37);
insert into ytp.comuna(nombre,idCiudad) values('Curaco de Vélez',37);
insert into ytp.comuna(nombre,idCiudad) values('Dalcahue',37);
insert into ytp.comuna(nombre,idCiudad) values('Puqueldón',37);
insert into ytp.comuna(nombre,idCiudad) values('Queilén',37);
insert into ytp.comuna(nombre,idCiudad) values('Quellón',37);
insert into ytp.comuna(nombre,idCiudad) values('Quemchi',37);
insert into ytp.comuna(nombre,idCiudad) values('Quinchao',37);
insert into ytp.comuna(nombre,idCiudad) values('Calbuco',38);
insert into ytp.comuna(nombre,idCiudad) values('Cochamó',38);
insert into ytp.comuna(nombre,idCiudad) values('Fresia',38);
insert into ytp.comuna(nombre,idCiudad) values('Frutillar',38);
insert into ytp.comuna(nombre,idCiudad) values('Llanquihue',38);
insert into ytp.comuna(nombre,idCiudad) values('Los Muermos',38);
insert into ytp.comuna(nombre,idCiudad) values('Maullín',38);
insert into ytp.comuna(nombre,idCiudad) values('Puerto Montt',38);
insert into ytp.comuna(nombre,idCiudad) values('Puerto Varas',38);
insert into ytp.comuna(nombre,idCiudad) values('Osorno',39);
insert into ytp.comuna(nombre,idCiudad) values('Puerto Octay',39);
insert into ytp.comuna(nombre,idCiudad) values('Purranque',39);
insert into ytp.comuna(nombre,idCiudad) values('Puyehue',39);
insert into ytp.comuna(nombre,idCiudad) values('Río Negro',39);
insert into ytp.comuna(nombre,idCiudad) values('San Pablo',39);
insert into ytp.comuna(nombre,idCiudad) values('San Juan de la Costa',39);
insert into ytp.comuna(nombre,idCiudad) values('Chaitén',40);
insert into ytp.comuna(nombre,idCiudad) values('Futaleufú',40);
insert into ytp.comuna(nombre,idCiudad) values('Hualaihué',40);
insert into ytp.comuna(nombre,idCiudad) values('Palena',40);
insert into ytp.comuna(nombre,idCiudad) values('Aysén',41);
insert into ytp.comuna(nombre,idCiudad) values('Cisnes',41);
insert into ytp.comuna(nombre,idCiudad) values('Guaitecas',41);
insert into ytp.comuna(nombre,idCiudad) values('Cochrane',42);
insert into ytp.comuna(nombre,idCiudad) values('OHiggins',42);
insert into ytp.comuna(nombre,idCiudad) values('Tortel',42);
insert into ytp.comuna(nombre,idCiudad) values('Coyhaique',43);
insert into ytp.comuna(nombre,idCiudad) values('Lago Verde',43);
insert into ytp.comuna(nombre,idCiudad) values('Chile Chico',44);
insert into ytp.comuna(nombre,idCiudad) values('Río Ibáñez',44);
insert into ytp.comuna(nombre,idCiudad) values('Antártica',45);
insert into ytp.comuna(nombre,idCiudad) values('Cabo de Hornos',45);
insert into ytp.comuna(nombre,idCiudad) values('Laguna Blanca',46);
insert into ytp.comuna(nombre,idCiudad) values('Punta Arenas',46);
insert into ytp.comuna(nombre,idCiudad) values('Río Verde',46);
insert into ytp.comuna(nombre,idCiudad) values('San Gregorio',46);
insert into ytp.comuna(nombre,idCiudad) values('Porvenir',47);
insert into ytp.comuna(nombre,idCiudad) values('Primavera',47);
insert into ytp.comuna(nombre,idCiudad) values('Timaukel',47);
insert into ytp.comuna(nombre,idCiudad) values('Natales',48);
insert into ytp.comuna(nombre,idCiudad) values('Torres del Paine',48);
insert into ytp.comuna(nombre,idCiudad) values('Colina',49);
insert into ytp.comuna(nombre,idCiudad) values('Lampa',49);
insert into ytp.comuna(nombre,idCiudad) values('Tiltil',49);
insert into ytp.comuna(nombre,idCiudad) values('Pirque',50);
insert into ytp.comuna(nombre,idCiudad) values('Puente Alto',50);
insert into ytp.comuna(nombre,idCiudad) values('San José de Maipo',50);
insert into ytp.comuna(nombre,idCiudad) values('Buin',51);
insert into ytp.comuna(nombre,idCiudad) values('Calera de Tango',51);
insert into ytp.comuna(nombre,idCiudad) values('Paine',51);
insert into ytp.comuna(nombre,idCiudad) values('San Bernardo',51);
insert into ytp.comuna(nombre,idCiudad) values('Alhué',52);
insert into ytp.comuna(nombre,idCiudad) values('Curacaví',52);
insert into ytp.comuna(nombre,idCiudad) values('María Pinto',52);
insert into ytp.comuna(nombre,idCiudad) values('Melipilla',52);
insert into ytp.comuna(nombre,idCiudad) values('San Pedro',52);
insert into ytp.comuna(nombre,idCiudad) values('Cerrillos',53);
insert into ytp.comuna(nombre,idCiudad) values('Cerro Navia',53);
insert into ytp.comuna(nombre,idCiudad) values('Conchalí',53);
insert into ytp.comuna(nombre,idCiudad) values('El Bosque',53);
insert into ytp.comuna(nombre,idCiudad) values('Estación Central',53);
insert into ytp.comuna(nombre,idCiudad) values('Huechuraba',53);
insert into ytp.comuna(nombre,idCiudad) values('Independencia',53);
insert into ytp.comuna(nombre,idCiudad) values('La Cisterna',53);
insert into ytp.comuna(nombre,idCiudad) values('La Granja',53);
insert into ytp.comuna(nombre,idCiudad) values('La Florida',53);
insert into ytp.comuna(nombre,idCiudad) values('La Pintana',53);
insert into ytp.comuna(nombre,idCiudad) values('La Reina',53);
insert into ytp.comuna(nombre,idCiudad) values('Las Condes',53);
insert into ytp.comuna(nombre,idCiudad) values('Lo Barnechea',53);
insert into ytp.comuna(nombre,idCiudad) values('Lo Espejo',53);
insert into ytp.comuna(nombre,idCiudad) values('Lo Prado',53);
insert into ytp.comuna(nombre,idCiudad) values('Macul',53);
insert into ytp.comuna(nombre,idCiudad) values('Maipú',53);
insert into ytp.comuna(nombre,idCiudad) values('Ñuñoa',53);
insert into ytp.comuna(nombre,idCiudad) values('Pedro Aguirre Cerda',53);
insert into ytp.comuna(nombre,idCiudad) values('Peñalolén',53);
insert into ytp.comuna(nombre,idCiudad) values('Providencia',53);
insert into ytp.comuna(nombre,idCiudad) values('Pudahuel',53);
insert into ytp.comuna(nombre,idCiudad) values('Quilicura',53);
insert into ytp.comuna(nombre,idCiudad) values('Quinta Normal',53);
insert into ytp.comuna(nombre,idCiudad) values('Recoleta',53);
insert into ytp.comuna(nombre,idCiudad) values('Renca',53);
insert into ytp.comuna(nombre,idCiudad) values('San Miguel',53);
insert into ytp.comuna(nombre,idCiudad) values('San Joaquín',53);
insert into ytp.comuna(nombre,idCiudad) values('San Ramón',53);
insert into ytp.comuna(nombre,idCiudad) values('Santiago',53);
insert into ytp.comuna(nombre,idCiudad) values('Vitacura',53);
insert into ytp.comuna(nombre,idCiudad) values('El Monte',54);
insert into ytp.comuna(nombre,idCiudad) values('Isla de Maipo',54);
insert into ytp.comuna(nombre,idCiudad) values('Padre Hurtado',54);
insert into ytp.comuna(nombre,idCiudad) values('Peñaflor',54);
insert into ytp.comuna(nombre,idCiudad) values('Talagante',54);

